language: swift
osx_image: xcode9.2
branches:
  only:
    - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Sketch\ Cache\ Cleaner.xcodeproj
  - MACOS_SCHEME="Sketch Cache Cleaner"
  matrix:
  - DESTINATION="arch=x86_64" SCHEME="$MACOS_SCHEME"  RUN_TESTS="NO"
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks